
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x9fh;\xb2ZNr\x9e\xd6F\x9ff\xdeZ/\x81'
    
_lr_action_items = {'PLUS':([11,13,14,18,23,24,25,26,27,28,29,],[-24,-25,21,21,-22,21,-23,-21,-20,-18,-19,]),'RPAREN':([11,13,18,23,25,26,27,28,29,],[-24,-25,25,-22,-23,-21,-20,-18,-19,]),'DIVIDE':([11,13,14,18,23,24,25,26,27,28,29,],[-24,-25,19,19,-22,19,-23,-21,-20,19,19,]),'NEWLINE':([0,1,2,3,4,5,9,10,11,13,14,16,23,24,25,26,27,28,29,],[2,2,-11,-2,-10,10,-1,-5,-24,-25,-8,-9,-22,-7,-23,-21,-20,-18,-19,]),'NUMBER':([6,12,15,17,19,20,21,22,],[11,11,11,11,11,11,11,11,]),'MINUS':([6,11,12,13,14,15,17,18,19,20,21,22,23,24,25,26,27,28,29,],[15,-24,15,-25,22,15,15,22,15,15,15,15,-22,22,-23,-21,-20,-18,-19,]),'EQUALS':([8,],[17,]),'EXIT':([0,1,2,3,4,5,9,10,11,13,14,16,23,24,25,26,27,28,29,],[4,4,-11,-2,-10,-6,-1,-5,-24,-25,-8,-9,-22,-7,-23,-21,-20,-18,-19,]),'LPAREN':([6,12,15,17,19,20,21,22,],[12,12,12,12,12,12,12,12,]),'PRINT':([0,1,2,3,4,5,9,10,11,13,14,16,23,24,25,26,27,28,29,],[6,6,-11,-2,-10,-6,-1,-5,-24,-25,-8,-9,-22,-7,-23,-21,-20,-18,-19,]),'INPUT':([0,1,2,3,4,5,9,10,11,13,14,16,23,24,25,26,27,28,29,],[7,7,-11,-2,-10,-6,-1,-5,-24,-25,-8,-9,-22,-7,-23,-21,-20,-18,-19,]),'TIMES':([11,13,14,18,23,24,25,26,27,28,29,],[-24,-25,20,20,-22,20,-23,-21,-20,20,20,]),'ID':([0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,19,20,21,22,23,24,25,26,27,28,29,],[8,8,-11,-2,-10,-6,13,16,-1,-5,-24,13,-25,-8,13,-9,13,13,13,13,13,-22,-7,-23,-21,-20,-18,-19,]),'$end':([1,2,3,4,5,9,10,11,13,14,16,23,24,25,26,27,28,29,],[0,-11,-2,-10,-6,-1,-5,-24,-25,-8,-9,-22,-7,-23,-21,-20,-18,-19,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stmts':([0,],[1,]),'expression':([6,12,15,17,19,20,21,22,],[14,18,23,24,26,27,28,29,]),'statement':([0,1,],[5,5,]),'stmt':([0,1,],[3,9,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stmts","S'",1,None,None,None),
  ('stmts -> stmts stmt','stmts',2,'p_stmts','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',96),
  ('stmts -> stmt','stmts',1,'p_stmts','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',97),
  ('suite -> statement','suite',1,'p_suite','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',106),
  ('suite -> LBRACE stmts RBRACE','suite',3,'p_suite','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',107),
  ('stmt -> statement NEWLINE','stmt',2,'p_stmt','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',113),
  ('stmt -> statement','stmt',1,'p_stmt','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',114),
  ('statement -> ID EQUALS expression','statement',3,'p_statement_assign','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',124),
  ('statement -> PRINT expression','statement',2,'p_statement_print','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',127),
  ('statement -> INPUT ID','statement',2,'p_statement_input','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',130),
  ('statement -> EXIT','statement',1,'p_statement_exit','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',133),
  ('statement -> NEWLINE','statement',1,'p_statement_newline','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',137),
  ('comparison -> expression EQ expression','comparison',3,'p_comparison','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',141),
  ('comparison -> expression NE expression','comparison',3,'p_comparison','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',142),
  ('comparison -> expression GT expression','comparison',3,'p_comparison','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',143),
  ('comparison -> expression GE expression','comparison',3,'p_comparison','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',144),
  ('comparison -> expression LT expression','comparison',3,'p_comparison','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',145),
  ('comparison -> expression LE expression','comparison',3,'p_comparison','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',146),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',154),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',155),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',156),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',157),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',164),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',167),
  ('expression -> NUMBER','expression',1,'p_expression_number','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',170),
  ('expression -> ID','expression',1,'p_expression_id','/home/ahmad/other/backup_dates/911205/parsPL/backup/2013_02_21_18_50_45/parser.py',173),
]
